-- This file has been split into separate query files:
--   db/query/account.sql
--   db/query/entry.sql
--   db/query/transfer.sql
--   db/query/user.sql
--
-- sqlc.yaml now loads those files directly.
